#!/usr/bin/env python3
"""
Phase 1: Early Transitions - Liquidsoap Implementation
========================================================

Implements bar-accurate early transition timing based on professional DJ
mixing research. Ensures transitions start 16+ bars before outro instead
of waiting for track boundary.

Key Principles:
- Detect outro from track analysis sections
- Calculate early crossfade start (16/24/32 bars before outro)
- Ensure bar-aligned timing with BPM accuracy
- Integrate seamlessly into Liquidsoap render pipeline

Research Foundation:
- Professional DJs start mixing 16+ bars before outro ends (research.md)
- Phrase boundaries must align musically (4/8/16/32 bar multiples)
- Early transitions prevent abrupt track switching
"""

import logging
from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, Any, List, Tuple
from enum import Enum

logger = logging.getLogger(__name__)


class EarlyTransitionModel(Enum):
    """Available early transition timing models."""
    FIXED_16_BARS = "fixed_16_bars"      # Standard: always 16 bars
    FIXED_24_BARS = "fixed_24_bars"      # Extended: 24 bars
    FIXED_32_BARS = "fixed_32_bars"      # Very early: 32 bars
    ADAPTIVE = "adaptive"                # Auto-detect based on track structure


@dataclass
class Phase1Config:
    """Configuration for Phase 1 Early Transitions."""
    enabled: bool = True
    model: EarlyTransitionModel = EarlyTransitionModel.FIXED_16_BARS
    
    # Fallback when outro not detected
    fallback_bars: int = 16
    
    # Validation
    require_outro_detection: bool = False  # If True, skip if no outro
    log_timing_details: bool = True
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for JSON serialization."""
        return {
            'enabled': self.enabled,
            'model': self.model.value,
            'fallback_bars': self.fallback_bars,
            'require_outro_detection': self.require_outro_detection,
            'log_timing_details': self.log_timing_details,
        }


@dataclass
class Phase1Metadata:
    """Timing data generated by Phase 1."""
    enabled: bool
    early_transition_bars: int
    outro_start_seconds: Optional[float]
    outro_detected: bool
    crossfade_start_seconds: Optional[float]
    crossfade_duration_bars: int
    seconds_per_bar: float
    bpm: float
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for transitions.json."""
        return {
            'enabled': self.enabled,
            'early_transition_bars': self.early_transition_bars,
            'outro_start_seconds': self.outro_start_seconds,
            'outro_detected': self.outro_detected,
            'crossfade_start_seconds': self.crossfade_start_seconds,
            'crossfade_duration_bars': self.crossfade_duration_bars,
            'seconds_per_bar': self.seconds_per_bar,
            'bpm': self.bpm,
        }


class Phase1EarlyTransitions:
    """
    Early Transition Timing Engine
    
    Transforms track boundary crossfades into professional DJ-style
    early transitions that start 16+ bars before outro.
    """
    
    def __init__(self, config: Phase1Config = None):
        """
        Initialize Phase 1 engine.
        
        Args:
            config: Phase1Config instance (uses defaults if None)
        """
        self.config = config or Phase1Config()
        self.logger = logging.getLogger(__name__)
        
        if self.config.enabled:
            self.logger.info(f"Phase 1 initialized - model: {self.config.model.value}")
    
    def apply_to_transition(
        self,
        transition: Dict[str, Any],
        outgoing_track: Dict[str, Any],
        incoming_track: Dict[str, Any],
    ) -> Tuple[Dict[str, Any], Phase1Metadata]:
        """
        Apply Phase 1 early transition timing to a single transition.
        
        Args:
            transition: Transition dict from transitions.json
                Required: target_bpm, overlap_bars
                Optional: crossfade_duration_seconds
            
            outgoing_track: Metadata for currently playing track
                Optional: outro_start_seconds, sections_json
            
            incoming_track: Metadata for next track
                Optional: drop_position_seconds
        
        Returns:
            (modified_transition, phase1_metadata)
            
        Raises:
            ValueError: If critical data missing and requirement fails
        """
        if not self.config.enabled:
            meta = Phase1Metadata(
                enabled=False,
                early_transition_bars=0,
                outro_start_seconds=None,
                outro_detected=False,
                crossfade_start_seconds=None,
                crossfade_duration_bars=transition.get('overlap_bars', 8),
                seconds_per_bar=0,
                bpm=transition.get('target_bpm', 120.0),
            )
            return transition, meta
        
        # Extract required fields
        bpm = transition.get('target_bpm')
        overlap_bars = transition.get('overlap_bars', 8)
        
        if not bpm:
            raise ValueError("transition['target_bpm'] is required")
        
        # Calculate timing constants
        seconds_per_bar = 240.0 / bpm
        
        # Detect outro position
        outro_start = self._detect_outro_start(outgoing_track)
        outro_detected = outro_start is not None
        
        # Determine early transition bars based on model
        early_bars = self._select_early_bars(
            self.config.model,
            outgoing_track,
            outro_detected,
        )
        
        # Calculate crossfade timing
        if outro_detected:
            # Start crossfade early_bars before outro
            crossfade_start_seconds = outro_start - (early_bars * seconds_per_bar)
        else:
            # Use fallback: assume generic ending structure
            track_duration = outgoing_track.get('duration_seconds', 180.0)
            # Assume outro starts at last 20 seconds (typical)
            estimated_outro_start = track_duration - 20.0
            crossfade_start_seconds = estimated_outro_start - (early_bars * seconds_per_bar)
            outro_start = None
        
        # Validate crossfade doesn't start before track exists
        if crossfade_start_seconds < 0:
            self.logger.warning(
                f"Phase 1: Crossfade would start before track begins. "
                f"Adjusting from {crossfade_start_seconds:.1f}s to 0s"
            )
            crossfade_start_seconds = 0
            early_bars = 0
        
        # Create metadata
        phase1_meta = Phase1Metadata(
            enabled=True,
            early_transition_bars=early_bars,
            outro_start_seconds=outro_start,
            outro_detected=outro_detected,
            crossfade_start_seconds=crossfade_start_seconds,
            crossfade_duration_bars=overlap_bars,
            seconds_per_bar=seconds_per_bar,
            bpm=bpm,
        )
        
        # Add to transition
        transition['phase_1_early_transitions'] = phase1_meta.to_dict()
        
        # Log details if enabled
        if self.config.log_timing_details:
            self._log_timing_details(
                transition.get('track_id'),
                early_bars,
                overlap_bars,
                seconds_per_bar,
                outro_start,
                crossfade_start_seconds,
            )
        
        return transition, phase1_meta
    
    def apply_to_playlist(
        self,
        transitions: List[Dict[str, Any]],
        tracks: Dict[str, Dict[str, Any]],
    ) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
        """
        Apply Phase 1 to entire playlist.
        
        Args:
            transitions: List of transition dicts
            tracks: Dict mapping track_id -> track metadata
        
        Returns:
            (modified_transitions, summary_stats)
        """
        if not self.config.enabled:
            return transitions, {'phase_1_enabled': False}
        
        modified = []
        stats = {
            'total_transitions': len(transitions),
            'applied': 0,
            'skipped': 0,
            'errors': 0,
            'early_bars_distribution': {},
            'phase_1_enabled': True,
        }
        
        for idx, trans in enumerate(transitions):
            try:
                # Get track metadata
                outgoing_id = trans.get('track_id')
                next_id = trans.get('next_track_id')
                
                outgoing = tracks.get(outgoing_id, {})
                incoming = tracks.get(next_id, {}) if next_id else {}
                
                # Apply Phase 1
                modified_trans, meta = self.apply_to_transition(
                    trans.copy(),
                    outgoing,
                    incoming,
                )
                
                modified.append(modified_trans)
                stats['applied'] += 1
                
                # Track distribution
                bars = meta.early_transition_bars
                if bars not in stats['early_bars_distribution']:
                    stats['early_bars_distribution'][bars] = 0
                stats['early_bars_distribution'][bars] += 1
                
            except Exception as e:
                self.logger.error(f"Phase 1 error on transition {idx}: {e}")
                modified.append(trans)
                stats['errors'] += 1
        
        self.logger.info(
            f"Phase 1 applied to {stats['applied']}/{stats['total_transitions']} "
            f"transitions (errors: {stats['errors']})"
        )
        self.logger.info(f"Early bars distribution: {stats['early_bars_distribution']}")
        
        return modified, stats
    
    def _detect_outro_start(self, track: Dict[str, Any]) -> Optional[float]:
        """
        Detect outro start position from track analysis.
        
        Checks multiple sources:
        1. Explicit outro_start_seconds field
        2. Track sections/analysis (if available)
        3. Duration-based estimation (fallback)
        
        Args:
            track: Track metadata dict
        
        Returns:
            Outro start time in seconds, or None if not detected
        """
        # Try explicit field first (most reliable)
        if 'outro_start_seconds' in track:
            seconds = track['outro_start_seconds']
            if seconds is not None and seconds >= 0:
                self.logger.debug(f"Outro detected at {seconds:.1f}s (explicit)")
                return seconds
        
        # Try analyzing sections if available
        sections = track.get('sections')
        if sections:
            outro_section = self._find_outro_section(sections)
            if outro_section:
                start = outro_section.get('start')
                if start is not None:
                    self.logger.debug(f"Outro detected at {start:.1f}s (from sections)")
                    return start
        
        # Try sections_json (JSON-encoded)
        sections_json = track.get('sections_json')
        if sections_json:
            try:
                import json
                sections = json.loads(sections_json)
                outro_section = self._find_outro_section(sections)
                if outro_section:
                    start = outro_section.get('start')
                    if start is not None:
                        self.logger.debug(f"Outro detected at {start:.1f}s (from sections_json)")
                        return start
            except Exception as e:
                self.logger.debug(f"Could not parse sections_json: {e}")
        
        # Fallback: estimate from duration (assume last 20 seconds)
        duration = track.get('duration_seconds')
        if duration:
            estimated = max(0, duration - 20.0)
            self.logger.debug(f"Outro estimated at {estimated:.1f}s (duration-based)")
            return estimated
        
        self.logger.debug("No outro detected")
        return None
    
    def _find_outro_section(self, sections: List[Dict]) -> Optional[Dict]:
        """
        Find outro section from section list.
        
        Looks for section with label containing 'outro' or 'end'.
        Falls back to last section if none found.
        
        Args:
            sections: List of section dicts with 'label' and 'start' keys
        
        Returns:
            Section dict, or None
        """
        if not sections:
            return None
        
        # Look for explicit outro/end labels
        for section in sections:
            label = section.get('label', '').lower()
            if 'outro' in label or 'end' in label:
                return section
        
        # Fall back to last section
        return sections[-1] if sections else None
    
    def _select_early_bars(
        self,
        model: EarlyTransitionModel,
        outgoing_track: Dict[str, Any],
        outro_detected: bool,
    ) -> int:
        """
        Select early transition bar count based on model.
        
        Args:
            model: Timing model enum
            outgoing_track: Track metadata
            outro_detected: Whether outro was detected
        
        Returns:
            Early transition bar count (16, 24, or 32)
        """
        if model == EarlyTransitionModel.FIXED_16_BARS:
            return 16
        
        elif model == EarlyTransitionModel.FIXED_24_BARS:
            return 24
        
        elif model == EarlyTransitionModel.FIXED_32_BARS:
            return 32
        
        elif model == EarlyTransitionModel.ADAPTIVE:
            # Adaptive: increase bar count for longer tracks
            duration = outgoing_track.get('duration_seconds', 180.0)
            if duration < 120:  # Short track (< 2 min)
                return 16
            elif duration < 240:  # Medium (2-4 min)
                return 24
            else:  # Long track (> 4 min)
                return 32
        
        else:
            # Unknown model, use default
            self.logger.warning(f"Unknown model {model}, using default 16 bars")
            return 16
    
    def _log_timing_details(
        self,
        track_id: str,
        early_bars: int,
        overlap_bars: int,
        seconds_per_bar: float,
        outro_start: Optional[float],
        crossfade_start: float,
    ) -> None:
        """Log detailed timing information for debugging."""
        outro_str = f"{outro_start:.1f}s" if outro_start else "not detected"
        msg = (
            f"Phase 1 Timing: track_id={track_id} | "
            f"early_transition={early_bars} bars | "
            f"crossfade={overlap_bars} bars | "
            f"bar_duration={seconds_per_bar:.2f}s | "
            f"outro_start={outro_str} | "
            f"crossfade_start={crossfade_start:.1f}s"
        )
        self.logger.info(msg)


def create_phase1_early_transitions(
    config_dict: Dict[str, Any] = None,
) -> Phase1EarlyTransitions:
    """
    Factory function to create Phase1 engine from config dict.
    
    Args:
        config_dict: Configuration dict (keys match Phase1Config fields)
    
    Returns:
        Initialized Phase1EarlyTransitions instance
    """
    if not config_dict:
        config = Phase1Config()
    else:
        # Build Phase1Config from dict
        model_str = config_dict.get('model', 'fixed_16_bars')
        try:
            model = EarlyTransitionModel(model_str)
        except ValueError:
            logger.warning(f"Unknown model {model_str}, using fixed_16_bars")
            model = EarlyTransitionModel.FIXED_16_BARS
        
        config = Phase1Config(
            enabled=config_dict.get('enabled', True),
            model=model,
            fallback_bars=config_dict.get('fallback_bars', 16),
            require_outro_detection=config_dict.get('require_outro_detection', False),
            log_timing_details=config_dict.get('log_timing_details', True),
        )
    
    return Phase1EarlyTransitions(config)


# ============================================================================
# LIQUIDSOAP CODE GENERATION HELPERS
# ============================================================================

def generate_liquidsoap_phase1(
    phase1_meta: Phase1Metadata,
) -> str:
    """
    Generate Liquidsoap code snippet for early transition timing.
    
    Args:
        phase1_meta: Phase1Metadata from apply_to_transition
    
    Returns:
        Liquidsoap code string for render.liq
    """
    if not phase1_meta.enabled:
        return "# Phase 1 disabled"
    
    # Convert timing to Liquidsoap variables
    crossfade_pos = phase1_meta.crossfade_start_seconds
    crossfade_duration = phase1_meta.crossfade_duration_bars * phase1_meta.seconds_per_bar
    
    liq_code = f"""
# ============================================================================
# PHASE 1: EARLY TRANSITIONS
# ============================================================================
# Early transition timing: start mixing {phase1_meta.early_transition_bars} bars before outro
# Outro at: {phase1_meta.outro_start_seconds if phase1_meta.outro_start_seconds else 'estimated'}s
# Crossfade starts at: {crossfade_pos:.2f}s
# Crossfade duration: {phase1_meta.crossfade_duration_bars} bars ({crossfade_duration:.2f}s)
# BPM: {phase1_meta.bpm:.1f}

let phase1_early_transition_enabled = true
let phase1_crossfade_start_seconds = {crossfade_pos:.3f}
let phase1_crossfade_duration_seconds = {crossfade_duration:.3f}
let phase1_early_bars = {phase1_meta.early_transition_bars}
let phase1_overlap_bars = {phase1_meta.crossfade_duration_bars}
"""
    
    return liq_code
